[listeners]
# host:port or unix socket (@ for abstract)
http1 = *:8080
uwsgi = 127.0.0.1:3000
fastcgi = /run/app.sock
metrics = 127.0.0.1:9999

[runtime]
# expose tokio runtime knobs
threads = 1
processes = 3
# min/max ?

[php]
docroot = ./data//php-app/
index = index.php
set = date.timezone=CET
ini = load-php.ini

[cgi]
docroot = ./data/cgi-bin/
index = index.cgi

[static]
docroot = ./data/static/
index = index.html

[routing]
# routing language?!?!

[logging]
# filterting
# formatting
# transport
